config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :le_blogs

  root "le_blogs#index"

  get "your_posts" => "le_blogs#your_posts"
  get "user_profile" => "le_blogs#user_profile"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :le_blog
	belongs_to :user
end

app/models/le_blog.rb
class LeBlog < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :le_blogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :username) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :username) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)


    respond_to do |format|
      if @comment.save
        format.html { redirect_to le_blog_path(id: @comment.le_blog_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :le_blog_id, :user_id)
    end
end

app/controllers/le_blogs_controller.rb
class LeBlogsController < ApplicationController
  before_action :set_le_blog, only: [:show, :edit, :update, :destroy]

  # GET /le_blogs
  # GET /le_blogs.json
  def index
    @le_blogs = LeBlog.all
  end

  def your_posts
  end

  def user_profile
    @user = User.find(params[:id])
  end
  # GET /le_blogs/1
  # GET /le_blogs/1.json
  def show
    @comment = Comment.new
  end

  # GET /le_blogs/new
  def new
    @le_blog = LeBlog.new
  end

  # GET /le_blogs/1/edit
  def edit
  end

  # POST /le_blogs
  # POST /le_blogs.json
  def create
    @le_blog = LeBlog.new(le_blog_params)

    respond_to do |format|
      if @le_blog.save
        format.html { redirect_to @le_blog, notice: 'Le blog was successfully created.' }
        format.json { render :show, status: :created, location: @le_blog }
      else
        format.html { render :new }
        format.json { render json: @le_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /le_blogs/1
  # PATCH/PUT /le_blogs/1.json
  def update
    respond_to do |format|
      if @le_blog.update(le_blog_params)
        format.html { redirect_to @le_blog, notice: 'Le blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @le_blog }
      else
        format.html { render :edit }
        format.json { render json: @le_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /le_blogs/1
  # DELETE /le_blogs/1.json
  def destroy
    @le_blog.destroy
    respond_to do |format|
      format.html { redirect_to le_blogs_url, notice: 'Le blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_le_blog
      @le_blog = LeBlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def le_blog_params
      params.require(:le_blog).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/le_blogs_helper.rb
module LeBlogsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :comment_entry %><br>
    <%= f.text_area :comment_entry %>
  </div>
  <div class="field cant-see-me">
    <%= f.number_field :le_blog_id, value: @le_blog.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">


<head>
  <title>TechTalentBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="colors">

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Your Posts", your_posts_path %> <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "New Post", new_le_blog_path %></li>
        
      </ul>
     <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Welcome, #{current_user.username}!", user_profile_path(id: current_user.id) %></li>
        
        <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



 <div class="container">
	<%= yield %>
 </div>

</body>
</html>

app/views/le_blogs/_form.html.erb
<%= form_for(@le_blog) do |f| %>
  <% if @le_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@le_blog.errors.count, "error") %> prohibited this le_blog from being saved:</h2>

      <ul>
      <% @le_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :blog_entry %><br>
    <%= f.text_area :blog_entry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/le_blogs/edit.html.erb
<h1>Editing Le Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @le_blog %> |
<%= link_to 'Back', le_blogs_path %>

app/views/le_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="banner">BLOGS</h1>

<div class="row">
 <% @le_blogs.each do |le_blog| %>
  <div class="col-md-6">
    <div class="panel panel-default">
      
      <div class="panel-heading">
       <%= link_to le_blog.title, le_blog %>
      </div>
        
        <div class="panel-body">
          <p> <%= link_to le_blog.user.username, user_profile_path(id: le_blog.user.id) %> </p>
          <p> <%= le_blog.blog_entry[0..200]%>...<%= link_to "Read More", le_blog %></p>
        </div>

      <div class="panel-footer">
        <% if le_blog.user.id == current_user.id %>
          <%= link_to 'Edit', edit_le_blog_path(le_blog), class: "btn btn-warning"%>
          <%= link_to 'Destroy', le_blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
          <p>Comments: <%= le_blog.comments.length %></p>
        
        </div>
    </div>
  </div>
 <% end %>
</div>

<br>

app/views/le_blogs/new.html.erb
<h1>New Le Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', le_blogs_path %>

app/views/le_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
	<div class="panel-heading">
	<%= @le_blog.title %>
	</div>
	
	<div class="panel-body">

		  <p><%= @le_blog.user.username %></p>
		  <p><em>Posted at <%= @le_blog.created_at.strftime("%m/%d/%Y, %I:%M%p")%></p>
		  <%= @le_blog.blog_entry %>
	</div>

	 <div class="panel-footer">
	 	<% if @le_blog.user.id == current_user.id %>
	<%= link_to 'Edit', edit_le_blog_path(@le_blog), class: "btn btn-primary" %>
	<% end %>
	<%= link_to 'Back', le_blogs_path, class: "btn btn-warning" %>

	 </div>
</div>

  
<h4>Make A Comment</h4>


<p>
 <%= render 'comments/form' %>
</p>


<div class="panel panel-danger">
	<div class="panel-heading"><h3>Comments</h3></div>

	<% @le_blog.comments.each do |comment| %>
	<div class="panel-body">
			<p><%= comment.author%></p>
			<p> posted at <%= comment.created_at.strftime("%m/%d/%Y")%>
			<p><%= comment.comment_entry %></p>
	</div>
<% end %>
</div>


 			

app/views/le_blogs/user_profile.html.erb
<h1><%= @user.username %> 's Profile </h1>

<p>
<%= @user.email %>
</p>

app/views/le_blogs/your_posts.html.erb
<h1>All of <%= current_user.username %>'s Posts</h1>

<div class="row">
 <% current_user.le_blogs.each do |le_blog| %>
  <div class="col-md-6">
    <div class="panel panel-default">
      
      <div class="panel-heading">
       <%= link_to le_blog.title, le_blog %>
      </div>
        
        <div class="panel-body">
          <p> <%= le_blog.blog_entry[0..200]%>...<%= link_to "Read More", le_blog %></p>
        </div>

      <div class="panel-footer">
        <% link_to 'Show', le_blog, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_le_blog_path(le_blog), class: "btn btn-warning"%>
        <%= link_to 'Destroy', le_blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>

    </div>
  </div>
 <% end %>
</div>